spring.application.name=todo_api

spring.datasource.url=jdbc:mysql://localhost:3306/todo_cse
spring.datasource.username=root
spring.datasource.password=lingesh9865
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
